spring:
  profiles:
    active: prod
  
  # 데이터베이스 설정
  datasource:
    url: jdbc:h2:mem:greenmate
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  # H2 Console 설정 (프로덕션에서는 보안상 비활성화 권장)
  h2:
    console:
      enabled: false  # 프로덕션에서는 false로 설정
      path: /h2-console
  
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false  # 프로덕션에서는 false
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false

# 서버 설정
server:
  port: 8080
  servlet:
    context-path: /
  
  # 에러 페이지 설정
  error:
    whitelabel:
      enabled: false
    include-message: never
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false

# 로깅 설정
logging:
  level:
    root: INFO
    com.greenmate: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /var/log/greenmate/application.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30

# 액추에이터 설정
management:
  endpoints:
    web:
      exposure:
        include: health, info
      base-path: /actuator
  endpoint:
    health:
      show-details: never  # 프로덕션에서는 never로 설정
  info:
    env:
      enabled: true

# CORS 설정
cors:
  allowed-origins:
    - http://103.244.108.70
    - https://103.244.108.70
    - http://localhost:3000
    - http://localhost:8080
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
    - PATCH
  allowed-headers: "*"
  allow-credentials: true
  max-age: 3600

# JWT 설정 (환경변수로 관리 권장)
jwt:
  secret: ${JWT_SECRET:mySecretKey}
  expiration: 86400000  # 24시간